name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master

      - name: Login to Github container register
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "./docker/Dockerfile"
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{github.repository}}:latest
            ghcr.io/${{github.repository}}:${{ github.ref_name }}
          build-args: NPM_TOKEN=${{ secrets.GITHUB_TOKEN }}
